from datetime import datetime
from models import db_drop_and_create_all, setup_db, Actor, Movie


movie1 = Movie(title='How to Steal a Million', year=datetime.strptime('1966/01/01', "%Y/%m/%d"))
movie2 = Movie(title='How to Marry a Millionaire', year=datetime.strptime('1953/01/01', "%Y/%m/%d"))
movie3 = Movie(title='Sunset Boulevard', year=datetime.strptime('1950/01/01', "%Y/%m/%d"))
movie4 = Movie(title='The Misfits' , year=datetime.strptime('1961/01/01', "%Y/%m/%d"))
movie5 = Movie(title='All About Eve', year=datetime.strptime('1950/01/01', "%Y/%m/%d"))
movie6 = Movie(title='Gentlemen Prefer Blondes', year=datetime.strptime('1953/01/01', "%Y/%m/%d"))
movie7 = Movie(title='The Seven Year Itch', year=datetime.strptime('1955/01/01', "%Y/%m/%d"))
movie8 = Movie(title='Pillow Talk', year=datetime.strptime('1959/01/01', "%Y/%m/%d"))
movie9 = Movie(title='High Society', year=datetime.strptime('1956/01/01', "%Y/%m/%d"))
movie10 = Movie(title='The King and I', year=datetime.strptime('1956/01/01', "%Y/%m/%d"))


movie1.insert()
movie2.insert()
movie3.insert()
movie4.insert()
movie5.insert()
movie6.insert()
movie7.insert()
movie8.insert()
movie9.insert()
movie10.insert()

artist1 = Actor(name='Marilyn Monroe', gender='female', age=23, catchphrase='Keep smiling, because life is a beautiful thing and theres so much to smile about.')
artist2 = Actor(name='Joan Crawford', gender='female', age=28, catchphrase='')
artist3 = Actor(name='Elizabet Taylor', gender='female', age=25, catchphrase='')
artist4 = Actor(name='Paul Newman', gender='male', age=35, catchphrase='If you dont have enemies, you dont have character.')
artist5 = Actor(name='Grace Kelly', gender='female', age=27, catchphrase='')
artist6 = Actor(name='Tommy Noonan', gender='male', age=28, catchphrase='') 
artist7 = Actor(name='Elliot Reid', gender='male', age=30, catchphrase='')
artist8 = Actor(name='Jane Russell', gender='female', age=27, catchphrase='')
artist9 = Actor(name='Charles Coburn', gender='male', age=67, catchphrase='')
artist10 = Actor(name='Gloria Swanson', gender='female', age=32, catchphrase='') 

artist1.insert()
artist2.insert()
artist3.insert()
artist4.insert()
artist5.insert()
artist6.insert()
artist7.insert()
artist8.insert()
artist9.insert()
artist10.insert()