"""empty message

Revision ID: 16a63d60259f
Revises: e9558453e458
Create Date: 2020-08-23 11:02:20.600678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a63d60259f'
down_revision = 'e9558453e458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'year')
    # ### end Alembic commands ###
