"""empty message

Revision ID: c759b9f1c946
Revises: 8e10b0b56c2c
Create Date: 2020-08-23 10:09:24.232959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c759b9f1c946'
down_revision = '8e10b0b56c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('imagelink', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('imagelink', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'imagelink')
    op.drop_column('Actor', 'imagelink')
    # ### end Alembic commands ###
