"""Drop link for Actor and Movie

Revision ID: d6435ddb762e
Revises: 16a63d60259f
Create Date: 2020-08-25 15:21:06.793730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6435ddb762e'
down_revision = '16a63d60259f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'imagelink')
    op.drop_column('movie', 'imagelink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('imagelink', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Actor', sa.Column('imagelink', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
