"""empty message

Revision ID: e9558453e458
Revises: c759b9f1c946
Create Date: 2020-08-23 10:33:48.873201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9558453e458'
down_revision = 'c759b9f1c946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
